In [4]:
import numpy as np

In [5]:
low_var=np.array([4,5,5,6,5,4,5,6,5])
high_var=np.array([1,9,2,10,3,11,4,12])

In [20]:
np.mean(low_var) # MEAN

np.float64(5.0)

In [19]:
np.median(low_var) # MEDIAN

np.float64(5.0)

In [21]:
np.ptp(low_var)  # RANGE

np.int64(2)

In [22]:
np.var(low_var) # VARIANCE

np.float64(0.4444444444444444)

In [23]:
np.var(high_var) # VARIANCE FOR 2ND VARIABLE

np.float64(17.25)

In [24]:
np.std(low_var) # STANDARD DEVIATION FOR 1ST VARIABLE

np.float64(0.6666666666666666)

In [25]:
np.std(high_var) # STANDARD DEVIATION FOR 2ND VARIABLE

np.float64(4.153311931459037)

Measuring Central Tendency Using Pandas

In [8]:
import pandas as pd

In [14]:
df=pd.DataFrame(low_var,columns=["chocolates"])

In [26]:
df.mean()

chocolates    5.0
dtype: float64

In [27]:
df.median()

chocolates    5.0
dtype: float64

In [28]:
df.mode()

   chocolates
0           5

In [29]:
df.var()

chocolates    0.5
dtype: float64

In [30]:
df.std()

chocolates    0.707107
dtype: float64